# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'AnimalRacing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimalRacing
pod 'Masonry', '~> 1.1.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

